version: '3'
services:
  bootstrapper-mysql:
    container_name: bootstrapper-mysql
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - appnet

networks:
  appnet:
    driver: bridge