version: 2
jobs:
  ruby-2.6.0:
    # Primary container image where all commands run
    
    docker:
      - image: circleci/ruby:2.6.0
    
      - image: mysql/mysql-server:5.7
        command: --default-authentication-plugin=mysql_native_password
        ports:
          - "3306:3306"
        environment:
          - MYSQL_ROOT_PASSWORD=root
        
    steps:
      - checkout

      # Bundle install dependencies
      - run:
          name: Install dependencies
          command: bundle install

      - run:
          name: Install SQL client
          command: sudo apt-get install mysql-client

      - run:
          name: Database Setup
          command: |
            mysql -uroot -proot < ./test/sql/user.sql ; mysql -uroot -proot < ./test/sql/drop.sql ; mysql -uroot -proot < ./test/sql/fixtures.sql

      - run:
          name: Run tests
          command: rake

workflows:
  version: 2
  build:
    jobs:
      - ruby-2.6.0