version: 2
jobs:
  ruby-2.6.0:
    # Primary container image where all commands run
    
    docker:
      - image: ruby:2.6.0
    
      - image: mysql/mysql-server:5.7
        command: --default-authentication-plugin=mysql_native_password
        ports:
          - "3306:3306"
        environment:
          - MYSQL_ROOT_PASSWORD=root
        
    steps:
      - checkout

      # Bundle install dependencies
      - run:
          name: Install dependencies
          command: bundle install

      - run:
          name: Database Setup
          command: |
            ./bin/test_setup

      - run:
          name: Run tests
          command: rake

      # collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
workflows:
  version: 2
  build:
    jobs:
      - ruby-2.6.0